In [3]:
import torch

In [4]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-16,  61,   6,  63,  88, -72])

In [5]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [10]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [14]:
linespace = torch.linspace(3,10, steps=5)
linespace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [15]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
emptylike

NameError: name 'empty' is not defined